### ISSUE TITLE
Unpublish previous versions from store.kde.org

### ISSUE THREAD

**Issue by Ashark** [gmm96/KDE-5-Template-Manager#10]
Could you please unpublish previous versions of the software? Because it is confusing to choose from:

![Screenshot of installation dialog](https://user-images.githubusercontent.com/22634975/139650332-61914539-a155-46f6-9ab7-dccd6d02cf56.png)

**Comment by gmm96** [comment]
@Ashark ok, done. It's true kde store doesn't handle very well different versions of same product.
