### ISSUE TITLE
Installs, but doesn't work at all

### ISSUE THREAD

**Issue by ZoidMonster** [gmm96/KDE-5-Template-Manager#12]
Operating System: EndeavourOS (Arch)
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.8-arch1-1 (64-bit)

I had "template-management_dolphin-service-menu-master" that didn't work.  I looked for uninstall.sh there was everything but no uninstall.sh

I installed "KDE-5-Template-Manager-v5" hoping it would fix it = still not working and had additional menu entries.
uninstalled "KDE-5-Template-Manager-v5" using it's uninstall.sh, and deleted all related files from ~/.bin (in PATH) ~/.local/share /kservices5/ServiceMenus, and it looked like I got rid of all traces; the menu and menu service settings dialog entries were all cleared.  I don't know if i need to remove anything else, nor where else to look, and there's no info here about what all the install script does.

I Rebooted just to make sure, and Reinstalled KDE-5-Template-Manager-v5, but it still does not work at all.

Steps:
Right click on file > Manage Template(s) > Create template from this file = Nothing happens at all!  )<:

Also:
The menu entry for directories is under:  Actions > Manage Template(s) > Create template from this directory.

That's inconsistent, the menu entries for files and directories should be in the same place in the menu.

**Comment by gmm96** [comment]
Thanks for your suggestion and sorry for the delay.
I will take a look of it tomorrow morning.

**Comment by ZoidMonster** [comment]
Thanks!

**Comment by gmm96** [comment]
Well, to be honest, I couldn't clearly see the issue or I have misundertood you. Anyway, let's get dipper. 

> I had "template-management_dolphin-service-menu-master" that didn't work. I looked for uninstall.sh there was everything but no uninstall.sh
> 
> I installed "KDE-5-Template-Manager-v5" hoping it would fix it = still not working and had additional menu entries. uninstalled "KDE-5-Template-Manager-v5" using it's uninstall.sh, and deleted all related files from ~/.bin (in PATH) ~/.local/share /kservices5/ServiceMenus, and it looked like I got rid of all traces; the menu and menu service settings dialog entries were all cleared. I don't know if i need to remove anything else, nor where else to look, and there's no info here about what all the install script does.

Sorry buddy, you are trying to **uninstall a different dolphin service menu** using the _uninstall.sh script_ from my project, which it is not possible. Every service menu should have its own uninstall.sh as installation is different between service menus. I am responsible of this project, not other's.

Anyway, watching the code of [install.sh from template-management_dolphin-service-menu](https://www.opencode.net/ashark/template-management_dolphin-service-menu/-/blob/master/install.sh), it seems you should find the **.desktop files** responsible for menu entries in the output directory from ``kf5-config --path services | cut -f1 -d:`` command and **binaries** in `$HOME/bin`, if you installed it not using admin rights. Remember, I'm talking about the other service menu which it's not mine.

> I Rebooted just to make sure, and Reinstalled KDE-5-Template-Manager-v5, but it still does not work at all.
> 
> Steps: Right click on file > Manage Template(s) > Create template from this file = Nothing happens at all! )<:
> 
> Also: The menu entry for directories is under: Actions > Manage Template(s) > Create template from this directory.
> 
> That's inconsistent, the menu entries for files and directories should be in the same place in the menu.

So, it's my service menu failing? What is exactly working wrong? Cannot you create a template from a regular file?

Talking about the different menu entry for files and directories, I have knowlegde of it and I think it's the best way to handle.
**KDE is responsible for dealing with mimetypes** this way, while you won't find a menu entry for templating files while double clicking a directory, and viceversa. If you know a better way to do it, please, don't hesitate and explain it to me.

Regards.

**Comment by ZoidMonster** [comment]
Again, to quote myself:

"I am using:  KDE-5-Template-Manager-v5" Seems to have installed right by running it's Install.sh.

Steps:  "Right click on file > Manage Template(s) > Create template from this file = Nothing happens at all!"  I believe a window should pop up with options?  I don't get anything at all.  Could I be missing a dependency or something like that?

I am not a developer and don't have a clue how to make menu entries, and even control their place in the menu,  just thought they should be in the same place for consistency.

**Comment by gmm96** [comment]
> Again, to quote myself:
> 
> "I am using: KDE-5-Template-Manager-v5" Seems to have installed right by running it's Install.sh.
> 
> Steps: "Right click on file > Manage Template(s) > Create template from this file = Nothing happens at all!" I believe a window should pop up with options? I don't get anything at all. Could I be missing a dependency or something like that?
> 
> I am not a developer and don't have a clue how to make menu entries, and even control their place in the menu, just thought they should be in the same place for consistency.

Mmm, that's really extrange. Please, make these checks in the next order, so we can discard some possible causes:
1. Check directory `$HOME/.bin/` exists and holds at least 5 scripts, which names starts by "Template...".
2. Check these scritps have execution rights. They gained this permisson when installing, but it maybe failed.
3. Check you already have kdialog package installed in your system, which should come in almost every KDE desktop environment. It's the only special dependency the project has.
4. Create a text file in your $HOME directory and run `$HOME/.bin/TemplateCreator.sh $HOME/<your text file>`. This should do the same function that the menu entry. A windows dialog should appear after that asking you the template arguments. 

Talking about the menu entries, you're completely right to be honest. It's just .desktop files arguments for creating menu entries in KDE doesn't work really well, specially if system has a different entry for every file type, so I thought this was the best solution to deal with it, as both file and directory menu entries should never appear at the same time.

Waiting for your answer and thanks for the support!!

**Comment by ZoidMonster** [comment]
In ~/.bin I have: TemplateCreator.sh, TemplateEditor.sh, TemplateEraser.sh (All executable), and TemplateManagerLocalization.sh and TemplateManagerTools.sh (Not executable).  I set the latter two to executable.

AHA!!!:  Tried the command line, and got:  "  line 16... Kdialog, no such command"  OK!  Not sure how or why, but I was missing Kdialog!

Installed Kdialog and viola' it works!  Yipieeeeeeeeee!!

Thanks!!!  (<:

**Comment by gmm96** [comment]
> In ~/.bin I have: TemplateCreator.sh, TemplateEditor.sh, TemplateEraser.sh (All executable), and TemplateManagerLocalization.sh and TemplateManagerTools.sh (Not executable). I set the latter two to executable.

It's my fault, I didn't notify users Kdialog is needed, I thought it came by default in every KDE environment.

I will update the readme in KDE store and here. Thanks for the report and I hope you like it!

Greetings.

**Comment by ZoidMonster** [comment]
I never thought KDialog to be a separate install either.

Oh, and you bet I will use it.  Templates are your freind!  (<:  Thanks!
