### ISSUE TITLE
Fix icons used in project

### ISSUE THREAD

**Issue by Ashark** [gmm96/KDE-5-Template-Manager#5]
Currently in TermplateManager.desktop the icon for main file is `favorite`. Probably should instead use the project's one TemplateManagerIcon.png. I guess it should be placed at some standard location (do not yet explored which exactly) by install.sh and then use its name in Icon= field.
Specifying absolute path to png works (in Dolphin the icon of the .desktop file itself changes), but using $HOME variable there does not work. So I am not sure for now how to implement it.
This icon is referenced also in install.sh and in uninstall.sh.

Some other icons are missing in my system. For example, xapp-favorite-symbolic in cuttlefish shows nothing. It is referenced in TemplateManager.desktop and in TemplateManagerTools.sh.

**Comment by gmm96** [comment]
To be honest, I have tried using the project's icon in the main service menu specifying absolute path to png file, but it always displays the icon corresponding to the first action in the menu (template creator). This is only happening on the service menu, you can properly see the icon navigating to the directory that keeps the service menu files using Dolphin. I don't know if it is currently a bug of Dolphin.

I was looking for a tool to check if certain icon exists in system, but without success. Maybe, I should use more common icons, like the ones used in template editor (edit) and template eraser (delete). Favorite icon may solve this issue.

**Comment by gmm96** [comment]
Well, command _kf5-config --path icon_ is currently working in my system, so I suppose I can give it another try installing the icon in one of these directories. 
On the other hand, I don't understand why some _kf5-config --path_ arguments goes in singular (icon) and others in plural (templates), but it is ok.

**Comment by gmm96** [comment]
After another look, _xdg-icon-resource_ seems to be the right command to (un)install icons in system.

**Comment by Ashark** [comment]
>  I don't know if it is currently a bug of Dolphin.

Probably yes, I also experience this. I did not yet searched or reported in bugs.kde.org

> I was looking for a tool to check if certain icon exists in system

You mean at runtime of the script? Or for you at develop time to choose an icon? If latter, then use Cuttlefish application.

**Comment by gmm96** [comment]
> You mean at runtime of the script? Or for you at develop time to choose an icon? If latter, then use Cuttlefish application.

I mean at runtime, so I would have alternatives to show if one icon is not installed in a system.
Well, I'm gonna move to more common icons (favorite, edit, delete), which I expect they'll be already installed in every system, and then will try custom png icons.

**Comment by gmm96** [comment]
Added more common icons in this [https://github.com/gmm96/KDE-5-Template-Manager/commit/9c38b8693c04c207177042fa09030a4305d0c185](commit). Closing this issue.
